# nginx, fastapi
version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8888:80"  # Nginx가 80 포트를 8888로 노출
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일 마운트
    networks:
      - web_network

  fastapi-1:
    container_name: fastapi-1
    build: 
      context: ../web/fastapi
      dockerfile: Dockerfile
      # args:
    environment:
      - HOST=0.0.0.0
      - PORT=8888
    volumes:
      - ../db_data:/app/data
    networks:
      - web_network

networks:
  web_network:
    external: true
    
  