# nginx, fastapi
version: '3'

services:
  # nginx-1:
  #   image: nginx
  #   ports: 
  #     - 80:${NGINX_PORT} # 80:8080
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - web_bridge

  fastapi-1:
    container_name: fastapi-1
    build: 
      context: ../web/fastapi
      dockerfile: Dockerfile
      # args:
    environment:
      - HOST=0.0.0.0
      - PORT=8888
    ports:
      - "8888:8888"
    networks:
      - web_bridge

networks:
  web_bridge:
    
  