# nginx, fastapi
version: '3'

services:
  nginx-1:
    image: nginx
    ports: 
      - 80:${NGINX_PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web_bridge

  fastAPI:
    image: demisto/fastapi
    ports:
      - "8888:8888"
    networks:
      - web_bridge

networks:
  web_bridge:
    
  