services:
  fastapi-ai:
    container_name: fastapi-ai
    build: 
      context: ./
      dockerfile: Dockerfile
      # args:
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
    - ./app:/app/
    - ../data:/app/data
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
    - web_network

networks:
  web_network:
    external: true